// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgiME9-009BeG6bhunAuj82SuGDIUyXqg',
    appId: '1:317498746666:web:3dc23c779f259803d4a053',
    messagingSenderId: '317498746666',
    projectId: 'p15-project',
    authDomain: 'p15-project.firebaseapp.com',
    storageBucket: 'p15-project.appspot.com',
    measurementId: 'G-VCDKTS96Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR4Ysr8kVG14zrbx_0DdiiMeLKShHdJko',
    appId: '1:317498746666:android:9f9b95399edc334dd4a053',
    messagingSenderId: '317498746666',
    projectId: 'p15-project',
    storageBucket: 'p15-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ1UdLJ1JOwYK4fMnP6I4wyhP_080_yyQ',
    appId: '1:317498746666:ios:e75db94ec1518231d4a053',
    messagingSenderId: '317498746666',
    projectId: 'p15-project',
    storageBucket: 'p15-project.appspot.com',
    iosClientId: '317498746666-dr3vv6e9c0i9halhit7p8etqstgaesgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ1UdLJ1JOwYK4fMnP6I4wyhP_080_yyQ',
    appId: '1:317498746666:ios:e75db94ec1518231d4a053',
    messagingSenderId: '317498746666',
    projectId: 'p15-project',
    storageBucket: 'p15-project.appspot.com',
    iosClientId: '317498746666-dr3vv6e9c0i9halhit7p8etqstgaesgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
